### ISSUE TITLE
Question about missing dev-gold.txt during training !

### ISSUE THREAD

**Issue by Quanbm2710** [SapienzaNLP/spring#12]
Hi ,
Thank you for your work.
I have set up a new environment, installed all the libraries, and the dataset I used to train this parser is LDC2017T10 (AMR 2.0). 
However, when I run this command line (python bin/train.py --config configs/config.yaml --direction amr) to train the AMR parser. I got this issue:
FileNotFoundError: [Errno 2] No such file or directory: '.../spring/data/tmp/dev-gold.txt'
I don't see any information about this file in the README also.
Did you forget to upload it or did I miss any steps?

Thanks.

**Comment by rexhinab** [comment]
Hello, 

Actually, the dev-gold.txt is automatically created [here](https://github.com/SapienzaNLP/spring/blob/39079940d028ba0dde4c1af60432be49f67d76f8/spring_amr/utils.py#L151). The error should arise due to the fact that the directory is not existing. You could try to create the directory data and its subdirectory tmp before running the training and it should be fine. 

Best!
