### ISSUE TITLE
Preprocessing for Spanish?

### ISSUE THREAD

**Issue by luciaelizabeth** [SapienzaNLP/spring#15]
Hi, I am trying to fine-tune SPRING on a small set of annotated Spanish AMRs to see how its cross-lingual parsing performance is. It seems the pre-processing is not working for Spanish (understandably), but we can't find anywhere in the code that calls for e.g. spaCy for English preprocessing that we could replace with something for Spanish. Can you help guide us to where this might be, or offer general clarification? Thanks!

**Comment by mbevila** [comment]
Hi! 

We don't use spaCy.

Unfortunately we don't support anything but English. The checkpoints are trained exclusively on English. To add the support for other languages, you would need to use mBART or mT5 instead of BART, then train on Spanish.

If you still do want to try Spanish even with the English model, well, the model takes as input strings. You could try, I suppose, to parse them into english AMR graphs.

**Comment by mbevila** [comment]
Closing this
